[platformio]
default_envs = Flowio-waveshare-esp32-s3

[common]
firmware_version = '"2.0.1"'
nextion_firmware_version = '"6.0.0"'

[env:Flowio-waveshare-esp32-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = freenove_esp32_s3_wroom
framework = arduino
lib_compat_mode = strict
lib_ldf_mode = chain
monitor_speed = 115200
monitor_filters = direct
debug_tool = esp-prog
debug_init_break = tbreak setup
upload_protocol = esptool

custom_version = ${common.firmware_version}
custom_cfgdocs_profile = waveshare
board_build.filesystem = spiffs
board_build.partitions = partition_waveshare_ota_16mb.csv
board_build.psram = enabled

extra_scripts =
	pre:scripts/generate_build_version.py
	pre:scripts/generate_datamodel.py
	pre:scripts/generate_runtimeui_manifest.py
	pre:scripts/prepare_spiffs_data.py
	post:scripts/export_binaries.py

build_flags =
	-std=c++17
	-std=gnu++17
	-D CORE_DEBUG_LEVEL=0
	-D CONFIG_LOG_COLORS=1
	-D FLOW_ENABLE_BUFFER_USAGE_TRACKING=1
	-D FLOW_EVENT_SUBSCRIBERS_MAX=56
	-D FLOW_HA_ONESHOT_DISCOVERY=1
	-D FLOW_HA_BOOT_TRACE=0
	-D FLOW_LOG_SERIAL_COLORS=1
	-D FIRMW=${common.firmware_version}
	-D TFT_FIRMW=${common.nextion_firmware_version}
	-D FLOW_ENABLE_TFT_S3=1
	-D ENABLE_ETHERNET=1
	-D ETH_TIMEOUT_MS=7000
	-D WIFI_TIMEOUT_MS=12000
	-D FLOW_ENABLE_BOOT_LOG_CAPTURE=1
	-D FLOW_RTC_PCF85063=1
	-D FLOW_TIME_PREFER_INTERNAL_RTC=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D BOARD_HAS_PSRAM
	-D CONFIG_ASYNC_TCP_STACK_SIZE=14336
	-D CONFIG_ASYNC_TCP_QUEUE_SIZE=16
	-mfix-esp32-psram-cache-issue
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections

build_unflags =
	-std=gnu++11
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=0

lib_deps =
	bblanchon/ArduinoJson @ ^6.21.5
	robtillaart/RunningMedian @ 0.3.9
	robtillaart/ADS1X15 @ 0.5.0
	https://github.com/pstolarz/Arduino-Temperature-Control-Library.git#OneWireNg
	pstolarz/OneWireNg @ ^0.14.1
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/Adafruit BusIO @ ^1.16.2
	adafruit/Adafruit GFX Library @ ^1.11.10
	adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
	https://github.com/adafruit/Adafruit_SHT4X.git
	https://github.com/adafruit/Adafruit_BMP280_Library.git
	https://github.com/adafruit/Adafruit_BME680.git
	https://github.com/wollewald/INA226_WE.git
	ESP32Async/AsyncTCP @ ^3.3.2
	ESP32Async/ESPAsyncWebServer @ ^3.6.0
