# Generate the compact runtime UI manifest used by the Waveshare web UI.

import json
import os
import re
from pathlib import Path

Import = type("Import", (), {})

try:
    Import("env")  # type: ignore
except Exception:
    env = None


def _get_project_dir():
    if env is not None:
        try:
            return env.get("PROJECT_DIR")
        except Exception:
            pass
    return os.getcwd()


def _find_runtime_ui_files(modules_root: Path, locale: str):
    # New model: module-local text manifests.
    preferred = sorted(modules_root.rglob(f"text/runtimeui.{locale}.json"))
    fallback = sorted(modules_root.rglob("text/runtimeui.json"))
    if preferred or fallback:
        by_dir = {path.parent: path for path in fallback}
        for path in preferred:
            by_dir[path.parent] = path
        return sorted(by_dir.values())

    # Legacy fallback during migration only.
    return sorted(modules_root.rglob("*RuntimeUi.json"))


def _parse_module_ids(module_id_path: Path):
    text = module_id_path.read_text(encoding="utf-8")

    enum_match = re.search(r"enum class ModuleId\s*:\s*uint8_t\s*\{(?P<body>.*?)\};", text, re.S)
    if not enum_match:
        raise RuntimeError("Unable to locate ModuleId enum")

    names = []
    for raw_line in enum_match.group("body").splitlines():
        line = raw_line.split("//", 1)[0].strip()
        if not line:
            continue
        if line.endswith(","):
            line = line[:-1].strip()
        if not line:
            continue
        if "=" in line:
            line = line.split("=", 1)[0].strip()
        names.append(line)

    numeric_by_name = {}
    for index, name in enumerate(names):
        numeric_by_name[name] = index

    alias_by_name = {}
    for match in re.finditer(r'case\s+ModuleId::([A-Za-z_][A-Za-z0-9_]*)\s*:\s*return\s+"([^"]+)";', text):
        alias_by_name[match.group(1)] = match.group(2)

    alias_to_numeric = {}
    for name, numeric in numeric_by_name.items():
        alias = alias_by_name.get(name)
        if alias:
            alias_to_numeric[alias] = numeric

    return numeric_by_name, alias_by_name, alias_to_numeric


def _resolve_module_id(raw_value, numeric_by_name, alias_to_numeric):
    if isinstance(raw_value, int):
        return raw_value
    if not isinstance(raw_value, str):
        raise RuntimeError(f"Invalid moduleId value: {raw_value!r}")

    if raw_value in numeric_by_name:
        return numeric_by_name[raw_value]
    if raw_value in alias_to_numeric:
        return alias_to_numeric[raw_value]
    raise RuntimeError(f"Unknown moduleId reference: {raw_value}")


def _json_dump(path: Path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def _c_string(text):
    if not text:
        return "nullptr"
    raw = text.encode("utf-8")
    out = '"'
    for byte in raw:
        ch = chr(byte)
        if ch == "\\":
            out += "\\\\"
        elif ch == '"':
            out += '\\"'
        elif 32 <= byte <= 126:
            out += ch
        else:
            # Use fixed-width octal escapes to avoid C/C++ `\\xNN...` greediness.
            out += f"\\{byte:03o}"
    out += '"'
    return out


def _write_header(out_path: Path, entries):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("/**\n")
        f.write(" * @file RuntimeUiManifest_Generated.h\n")
        f.write(" * @brief Auto-generated compact runtime UI manifest lookup.\n")
        f.write(" */\n\n")
        f.write("// This file is generated by scripts/generate_runtimeui_manifest.py\n")
        f.write("// Do not edit manually.\n\n")
        f.write('#include "Core/RuntimeUi.h"\n\n')
        f.write("enum class RuntimeUiActionInputType : uint8_t {\n")
        f.write("    None = 0,\n")
        f.write("    Bool,\n")
        f.write("    UInt32\n")
        f.write("};\n\n")
        f.write("struct RuntimeUiActionManifestItem {\n")
        f.write("    RuntimeUiId runtimeId;\n")
        f.write("    const char* actionId;\n")
        f.write("    const char* command;\n")
        f.write("    const char* inputName;\n")
        f.write("    RuntimeUiActionInputType inputType;\n")
        f.write("};\n\n")
        f.write("struct RuntimeUiManifestItem {\n")
        f.write("    RuntimeUiId id;\n")
        f.write("    const char* key;\n")
        f.write("    const char* type;\n")
        f.write("    const char* unit;\n")
        f.write("};\n\n")
        f.write("inline constexpr RuntimeUiActionManifestItem kRuntimeUiActionManifestItems[] = {\n")
        input_types = {
            "none": "RuntimeUiActionInputType::None",
            "bool": "RuntimeUiActionInputType::Bool",
            "uint32": "RuntimeUiActionInputType::UInt32",
        }
        flattened_actions = [
            (entry, action)
            for entry in entries
            for action in entry.get("actions") or []
        ]
        for entry, action in flattened_actions:
            action_input = action.get("input") or {}
            f.write(
                "    {"
                f"{entry['id']}, "
                f"{_c_string(action['id'])}, "
                f"{_c_string(action['command'])}, "
                f"{_c_string(action_input.get('name') or '')}, "
                f"{input_types[action_input.get('type', 'none')]}"
                "},\n"
            )
        if not flattened_actions:
            f.write("    {0, nullptr, nullptr, nullptr, RuntimeUiActionInputType::None},\n")
        f.write("};\n\n")
        f.write(f"inline constexpr size_t kRuntimeUiActionManifestItemCount = {len(flattened_actions)}U;\n\n")
        f.write("inline constexpr RuntimeUiManifestItem kRuntimeUiManifestItems[] = {\n")
        for entry in entries:
            f.write(
                "    {"
                f"{entry['id']}, "
                f"{_c_string(entry['key'])}, "
                f"{_c_string(entry['type'])}, "
                f"{_c_string(entry.get('unit') or '')}"
                "},\n"
            )
        f.write("};\n\n")
        f.write(
            "inline constexpr size_t kRuntimeUiManifestItemCount = "
            "(sizeof(kRuntimeUiManifestItems) / sizeof(kRuntimeUiManifestItems[0]));\n\n"
        )
        f.write("inline constexpr const RuntimeUiManifestItem* findRuntimeUiManifestItem(RuntimeUiId id)\n")
        f.write("{\n")
        f.write("    for (size_t i = 0; i < kRuntimeUiManifestItemCount; ++i) {\n")
        f.write("        if (kRuntimeUiManifestItems[i].id == id) return &kRuntimeUiManifestItems[i];\n")
        f.write("    }\n")
        f.write("    return nullptr;\n")
        f.write("}\n")
        f.write("\ninline constexpr const RuntimeUiActionManifestItem* findRuntimeUiActionManifestItem(\n")
        f.write("    RuntimeUiId runtimeId, const char* actionId)\n")
        f.write("{\n")
        f.write("    if (!actionId) return nullptr;\n")
        f.write("    for (size_t i = 0; i < kRuntimeUiActionManifestItemCount; ++i) {\n")
        f.write("        const RuntimeUiActionManifestItem& item = kRuntimeUiActionManifestItems[i];\n")
        f.write("        if (item.runtimeId != runtimeId) continue;\n")
        f.write("        const char* left = item.actionId;\n")
        f.write("        const char* right = actionId;\n")
        f.write("        while (*left != '\\0' && *left == *right) { ++left; ++right; }\n")
        f.write("        if (*left == '\\0' && *right == '\\0') return &item;\n")
        f.write("    }\n")
        f.write("    return nullptr;\n")
        f.write("}\n")


def _write_manifest_json_header(out_path: Path, manifest: dict):
    payload = json.dumps(manifest, ensure_ascii=True, indent=2)
    delimiter = "RUI"
    if f"){delimiter}\"" in payload:
        raise RuntimeError("Runtime manifest payload collides with raw-string delimiter")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("/**\n")
        f.write(" * @file RuntimeUiManifestJson_Generated.h\n")
        f.write(" * @brief Auto-generated runtime manifest JSON payload for WebInterface API.\n")
        f.write(" */\n\n")
        f.write("// This file is generated by scripts/generate_runtimeui_manifest.py\n")
        f.write("// Do not edit manually.\n\n")
        f.write("inline constexpr const char kRuntimeUiManifestJson[] = R\"")
        f.write(delimiter)
        f.write("(\n")
        f.write(payload)
        f.write("\n)")
        f.write(delimiter)
        f.write("\";\n")


def _normalize_lang_code(value: str):
    if not value:
        return "fr"
    value = value.strip().lower()
    if value.startswith("en"):
        return "en"
    return "fr"


def _write_alarm_text_catalog_header(out_path: Path, entries_fr, entries_en):
    def flags_for_key(entries, key):
        for entry in entries:
            if entry.get("key") != key:
                continue
            flags = entry.get("flags")
            if not isinstance(flags, list):
                return {}
            out = {}
            for flag in flags:
                if not isinstance(flag, dict):
                    continue
                mask = flag.get("mask")
                label = flag.get("label")
                if isinstance(mask, int) and isinstance(label, str):
                    out[int(mask)] = label
            return out
        return {}

    fr_flags = flags_for_key(entries_fr, "alarms.active_mask")
    en_flags = flags_for_key(entries_en, "alarms.active_mask")
    masks = sorted(set(fr_flags.keys()) | set(en_flags.keys()))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("/**\n")
        f.write(" * @file RuntimeUiAlarmText_Generated.h\n")
        f.write(" * @brief Auto-generated FR/EN alarm flag labels for local TFT rendering.\n")
        f.write(" */\n\n")
        f.write("// This file is generated by scripts/generate_runtimeui_manifest.py\n")
        f.write("// Do not edit manually.\n\n")
        f.write("#include <stddef.h>\n")
        f.write("#include <stdint.h>\n\n")
        f.write("struct RuntimeUiAlarmFlagLabelItem {\n")
        f.write("    uint32_t mask;\n")
        f.write("    const char* fr;\n")
        f.write("    const char* en;\n")
        f.write("};\n\n")
        f.write("inline constexpr RuntimeUiAlarmFlagLabelItem kRuntimeUiAlarmActiveFlagLabels[] = {\n")
        for mask in masks:
            fr_label = fr_flags.get(mask, "")
            en_label = en_flags.get(mask, fr_label)
            f.write(
                "    {"
                f"{mask}, "
                f"{_c_string(fr_label)}, "
                f"{_c_string(en_label)}"
                "},\n"
            )
        f.write("};\n\n")
        f.write(
            "inline constexpr size_t kRuntimeUiAlarmActiveFlagLabelCount = "
            "(sizeof(kRuntimeUiAlarmActiveFlagLabels) / sizeof(kRuntimeUiAlarmActiveFlagLabels[0]));\n\n"
        )
        f.write("inline constexpr bool runtimeUiIsEnglishLang(const char* lang)\n")
        f.write("{\n")
        f.write("    if (!lang) return false;\n")
        f.write("    char a = lang[0];\n")
        f.write("    char b = lang[1];\n")
        f.write("    if (a >= 'A' && a <= 'Z') a = (char)(a + ('a' - 'A'));\n")
        f.write("    if (b >= 'A' && b <= 'Z') b = (char)(b + ('a' - 'A'));\n")
        f.write("    return a == 'e' && b == 'n';\n")
        f.write("}\n\n")
        f.write("inline constexpr const char* runtimeUiAlarmActiveFlagLabel(uint32_t mask, const char* lang)\n")
        f.write("{\n")
        f.write("    const bool english = runtimeUiIsEnglishLang(lang);\n")
        f.write("    for (size_t i = 0; i < kRuntimeUiAlarmActiveFlagLabelCount; ++i) {\n")
        f.write("        if (kRuntimeUiAlarmActiveFlagLabels[i].mask == mask) {\n")
        f.write("            return english ? kRuntimeUiAlarmActiveFlagLabels[i].en : kRuntimeUiAlarmActiveFlagLabels[i].fr;\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    return \"\";\n")
        f.write("}\n")


def _load_text_payload(path: Path):
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return data if isinstance(data, dict) else None


def _load_i18n_for_runtime_file(runtime_file: Path, locale: str):
    # runtime_file is expected under <module>/text/
    search = []
    if runtime_file.parent.name == "text":
        search.append(runtime_file.parent / f"i18n.{locale}.json")
        search.append(runtime_file.parent / "i18n.json")
    translations = {}
    for path in search:
        if not path.exists():
            continue
        payload = _load_text_payload(path)
        if not payload:
            continue
        src = payload.get("translations") if isinstance(payload.get("translations"), dict) else payload
        for k, v in src.items():
            if isinstance(k, str) and isinstance(v, str) and k.strip():
                translations[k.strip()] = v
    return translations


def _find_i18n_files(modules_root: Path, locale: str):
    preferred = sorted(modules_root.rglob(f"text/i18n.{locale}.json"))
    fallback = sorted(modules_root.rglob("text/i18n.json"))
    by_dir = {path.parent: path for path in fallback}
    for path in preferred:
        by_dir[path.parent] = path
    return sorted(by_dir.values())


def _load_i18n_catalog(modules_root: Path, locale: str):
    translations = {}
    for path in _find_i18n_files(modules_root, locale):
        payload = _load_text_payload(path)
        if not payload:
            continue
        src = payload.get("translations") if isinstance(payload.get("translations"), dict) else payload
        for k, v in src.items():
            if isinstance(k, str) and isinstance(v, str) and k.strip():
                translations[k.strip()] = v
    return translations


def _resolve_i18n_tokens(node, translations):
    if isinstance(node, list):
        return [_resolve_i18n_tokens(item, translations) for item in node]
    if not isinstance(node, dict):
        return node
    out = {}
    for key, value in node.items():
        if key.endswith("_t") and isinstance(value, str):
            base_key = key[:-2]
            token = value.strip()
            out[base_key] = translations.get(token, token)
        else:
            out[key] = _resolve_i18n_tokens(value, translations)
    return out


def _collect_entries_for_locale(modules_root: Path, locale: str, numeric_by_name, alias_by_name, alias_to_numeric):
    global_translations = _load_i18n_catalog(modules_root, locale)
    entries = []
    seen_runtime_ids = {}
    for path in _find_runtime_ui_files(modules_root, locale):
        payload = _load_text_payload(path)
        if not isinstance(payload, dict):
            raise RuntimeError(f"RuntimeUi file must contain an object: {path}")

        translations = dict(global_translations)
        translations.update(_load_i18n_for_runtime_file(path, locale))
        payload = _resolve_i18n_tokens(payload, translations)

        module_ref = payload.get("moduleId")
        module_numeric = _resolve_module_id(module_ref, numeric_by_name, alias_to_numeric)
        module_name = None
        for name, numeric in numeric_by_name.items():
            if numeric == module_numeric:
                module_name = name
                break
        if module_name is None or module_name in ("Unknown", "Count"):
            raise RuntimeError(f"Invalid runtime UI module id in {path}: {module_ref}")

        module_alias = alias_by_name.get(module_name, "unknown")
        values = payload.get("values")
        if not isinstance(values, list):
            raise RuntimeError(f"RuntimeUi file missing values array: {path}")

        for value in values:
            if not isinstance(value, dict):
                raise RuntimeError(f"RuntimeUi value entry must be an object: {path}")

            value_id = value.get("valueId")
            if not isinstance(value_id, int) or value_id <= 0 or value_id >= 100:
                raise RuntimeError(f"Invalid valueId in {path}: {value_id!r}")

            runtime_id = module_numeric * 100 + value_id
            declared_runtime_id = value.get("runtimeId")
            if declared_runtime_id is not None and declared_runtime_id != runtime_id:
                raise RuntimeError(
                    f"runtimeId mismatch in {path}: declared={declared_runtime_id} expected={runtime_id}"
                )

            if runtime_id in seen_runtime_ids:
                raise RuntimeError(
                    f"Duplicate runtimeId {runtime_id} in {path} and {seen_runtime_ids[runtime_id]}"
                )
            seen_runtime_ids[runtime_id] = path

            display = value.get("display")
            if display is not None:
                if display == "gauge":
                    display = "circ-gauge"
                if display not in ("circ-gauge", "horiz-gauge", "badge", "boolean", "time", "value", "flags"):
                    raise RuntimeError(f"Invalid display in {path}: {display!r}")
            else:
                value_type = value.get("type")
                if value_type == "bool":
                    display = "boolean"
                else:
                    display = "value"

            display_config = value.get("displayConfig")
            if display_config is not None and not isinstance(display_config, dict):
                raise RuntimeError(f"displayConfig must be an object in {path}: {display_config!r}")

            actions = value.get("actions")
            if actions is not None and not isinstance(actions, list):
                raise RuntimeError(f"actions must be an array in {path}: {actions!r}")
            normalized_actions = []
            seen_action_ids = set()
            for action in actions or []:
                if not isinstance(action, dict):
                    raise RuntimeError(f"action must be an object in {path}: {action!r}")
                action_id = action.get("id")
                command = action.get("command")
                if not isinstance(action_id, str) or not re.fullmatch(r"[a-z][a-z0-9_.-]{0,31}", action_id):
                    raise RuntimeError(f"invalid action id in {path}: {action_id!r}")
                if action_id in seen_action_ids:
                    raise RuntimeError(f"duplicate action id {action_id!r} for runtimeId {runtime_id} in {path}")
                seen_action_ids.add(action_id)
                if not isinstance(command, str) or not re.fullmatch(r"[a-z][a-z0-9_.-]{0,63}", command):
                    raise RuntimeError(f"invalid action command in {path}: {command!r}")
                presentation = action.get("presentation")
                if presentation not in ("switch", "button"):
                    raise RuntimeError(f"unsupported action presentation in {path}: {presentation!r}")

                action_input = action.get("input")
                if action_input is None:
                    normalized_input = {"type": "none"}
                else:
                    if not isinstance(action_input, dict):
                        raise RuntimeError(f"action input must be an object in {path}: {action_input!r}")
                    input_name = action_input.get("name")
                    input_type = action_input.get("type")
                    if not isinstance(input_name, str) or not re.fullmatch(r"[a-z][a-z0-9_]{0,31}", input_name):
                        raise RuntimeError(f"invalid action input name in {path}: {input_name!r}")
                    if input_type not in ("bool", "uint32"):
                        raise RuntimeError(f"unsupported action input type in {path}: {input_type!r}")
                    normalized_input = {"name": input_name, "type": input_type}

                refresh_domains = action.get("refreshDomains", [])
                if not isinstance(refresh_domains, list) or any(
                    not isinstance(domain, str) or not re.fullmatch(r"[a-z][a-z0-9_-]{0,31}", domain)
                    for domain in refresh_domains
                ):
                    raise RuntimeError(f"invalid action refreshDomains in {path}: {refresh_domains!r}")

                normalized_actions.append({
                    "id": action_id,
                    "command": command,
                    "presentation": presentation,
                    "input": normalized_input,
                    "refreshDomains": refresh_domains,
                })

            entry = {
                "id": runtime_id,
                "runtimeId": runtime_id,
                "moduleId": module_numeric,
                "module": module_alias,
                "valueId": value_id,
                "key": value["key"],
                "label": value["label"],
                "type": value["type"],
                "domain": value["domain"],
                "group": value.get("group"),
                "unit": value.get("unit"),
                "decimals": value.get("decimals"),
                "order": value.get("order"),
                "enum": value.get("enum"),
                "flags": value.get("flags"),
                "display": display,
                "displayConfig": display_config,
            }
            if normalized_actions:
                entry["actions"] = normalized_actions
            entries.append(entry)

    entries.sort(key=lambda item: (item["domain"], item.get("group") or "", item.get("order") or 0, item["id"]))
    return entries


def main():
    project_dir = Path(_get_project_dir())
    modules_root = project_dir / "src" / "Modules"
    module_id_path = project_dir / "src" / "Core" / "ModuleId.h"
    out_header_path = project_dir / "src" / "Core" / "Generated" / "RuntimeUiManifest_Generated.h"
    out_json_header_path = project_dir / "src" / "Core" / "Generated" / "RuntimeUiManifestJson_Generated.h"
    out_alarm_text_header_path = project_dir / "src" / "Core" / "Generated" / "RuntimeUiAlarmText_Generated.h"
    locale = _normalize_lang_code(os.getenv("FLOW_CFGDOC_LOCALE", "fr"))

    numeric_by_name, alias_by_name, alias_to_numeric = _parse_module_ids(module_id_path)
    entries = _collect_entries_for_locale(modules_root, locale, numeric_by_name, alias_by_name, alias_to_numeric)
    manifest = {
        "ok": True,
        "values": entries,
    }
    write_manifest_json = os.getenv("FLOW_RUNTIMEUI_WRITE_JSON", "0").strip().lower() in ("1", "true", "yes", "on")
    if write_manifest_json:
        out_json_path = project_dir / "data" / "webinterface" / "runtimeui.json"
        _json_dump(out_json_path, manifest)
    _write_header(out_header_path, entries)
    _write_manifest_json_header(out_json_header_path, manifest)

    entries_fr = _collect_entries_for_locale(modules_root, "fr", numeric_by_name, alias_by_name, alias_to_numeric)
    entries_en = _collect_entries_for_locale(modules_root, "en", numeric_by_name, alias_by_name, alias_to_numeric)
    _write_alarm_text_catalog_header(out_alarm_text_header_path, entries_fr, entries_en)


main()
